name: codal-buildpr

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: letssteam/makecode-toolchain:latest
      options: --user 1001 --security-opt no-new-privileges
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      REPO_PATH: codal/libraries/${{ github.event.repository.name }}
      REPO_URL: ${{ github.event.repository.clone_url }}
    steps:
      - name: checkout codal
        uses: actions/checkout@v2
        with:
          repository: letssteam/codal
          path: codal

      - name: checkout codal-core
        uses: actions/checkout@v2
        with:
          repository: letssteam/codal-core
          path: codal/libraries/codal-core

      - name: checkout codal-stm32
        uses: actions/checkout@v2
        with:
          repository: letssteam/codal-stm32
          path: codal/libraries/codal-stm32
          submodules: recursive

      - name: checkout codal-stm32-STEAM32_WB55RG
        uses: actions/checkout@v2
        with:
          repository: letssteam/codal-stm32-STEAM32_WB55RG
          path: codal/libraries/codal-stm32-STEAM32_WB55RG
          submodules: recursive
          
      - name: checkout PR
        uses: actions/checkout@v2
        with:
          path: ${{env.REPO_PATH}}

      - name: create codal.json
        run: |
          echo \
            "{
              \"target\": {
              \"name\": \"$REPO_NAME\", 
              \"url\": \"$REPO_URL\",
              \"branch\": \"main\",
              \"type\": \"git\",
              \"dev\": true
              }
            }" > codal/codal.json
      - name: build PR
        run: |
          cd codal
          ./build.py -c
